function new_index = get_other_pyramid_level_axis_index(current_index,...
    current_level_axis_length, new_level_axis_length)
new_index = round((current_index - 1) *...
    new_level_axis_length / current_level_axis_length + 1);
end